GET http://localhost:8000/tasks/ HTTP/1.1
Token: I0akNeOFnDoJ1unyz2HfioPg3KL5odMI90ZfHqRIhmA3JB2ft3

###

POST http://localhost:8000/tasks/ HTTP/1.1
Content-Type: application/json

{
    "title": "test",
    "description": "test"
}

###

PUT http://localhost:8000/tasks/ HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "title": "no",
    "description": "yes",
    "done": true
}

###

DELETE http://localhost:8000/tasks/1 HTTP/1.1